[DEVOPS-531] Handle separate distro configs
iris-GmbH/iris-kas pull request #111
Opened 2022-07-15 11:58 UTC by Jasper-Ben

Handle distro config split for deploy and maintenance firmware in
Makefile and CI

2022-07-15 12:02 UTC, Jasper-Ben commented
merge after https://github.com/iris-GmbH/meta-iris-base/pull/125

2022-07-15 13:28 UTC, Eximmius commented
https://wiki.iris-sensing.net/x/xQF1Fw does something needs to be updated here afterwards?

2022-07-15 16:19 UTC, Jasper-Ben commented
> https://wiki.iris-sensing.net/x/xQF1Fw does something needs to be updated here afterwards?

yes. However, merging is currently still blocked by introduction of gitlab runner builds anyways. Will update afterwards.

2022-07-15 16:33 UTC, Jasper-Ben commented
it would actually be smarter to use the distro configurations as new base config and statically include the configuration currently in the base config. This would remove an unnecessary, but currently mandatory dynamic include.

Reminder to myself to fix this.

2022-07-17 08:52 UTC, martin31821 approved these changes

2022-07-19 10:40 UTC, DanielBaumgart requested changes

2022-07-19 10:40 UTC, DanielBaumgart commented on kas-irma6-base-common.yml
> +    refspec: "feature/jaor/deploy_maintenance_distro_configs"
Vor dem Merge wieder auf "develop" stellen!

2022-07-26 12:02 UTC, Jasper-Ben commented on kas-irma6-base-common.yml
> +    refspec: "feature/jaor/deploy_maintenance_distro_configs"
Done

2022-07-29 07:19 UTC, DanielBaumgart approved these changes

2022-07-29 09:54 UTC, Jasper-Ben commented
Merged into https://github.com/iris-GmbH/iris-kas/pull/112

2022-07-29 09:54 UTC, closed without merging