Introduce meta-iris-thirdparty and meta-webserver
iris-GmbH/iris-kas pull request #98
Opened 2022-04-13 14:23 UTC by niklas152

2022-04-13 19:30 UTC, Jasper-Ben requested changes

2022-04-13 19:30 UTC, Jasper-Ben commented on kas-irma6-base.yml
> +    refspec: "develop"
Should be `dunfell`

2022-04-14 07:22 UTC, ThomasWNoack commented
**Maintainer Checklist**

- Is there a changelog entry? **NO**
- Was a Jenkins run performed? **NO**

2022-04-14 07:22 UTC, ThomasWNoack requested changes
Please add a changelog entry and do a Jenkins run on the intranet (and link the pipeline number here).

2022-04-25 13:45 UTC, DanielBaumgart approved these changes

2022-04-25 17:41 UTC, Jasper-Ben approved these changes

2022-05-02 15:56 UTC, merged